apiVersion: v1
kind: PersistentVolume
metadata:
  name: xml2pdf-pv
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/_geol/wd/xml_to_pdf"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xml2pdf-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  volumeName: xml2pdf-pv

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: xml2pdf-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xml2pdf
  template:
    metadata:
      labels:
        app: xml2pdf
    spec:
      containers:
      - name: xml2pdf
        image: gimmyhat/xml_to_pdf:latest
        ports:
        - containerPort: 10016
        env:
        - name: USER
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: user
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: pwd
        volumeMounts:
        - mountPath: "/data"
          name: data-volume
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: xml2pdf-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: xml2pdf-service
spec:
  selector:
    app: xml2pdf
  ports:
    - protocol: TCP
      port: 10016
      targetPort: 10016
      nodePort: 31001
  type: NodePort
